### ISSUE TITLE
exec: "ssh": executable file not found in $PATH

### ISSUE THREAD

**Issue by lingfish** [lingfish/proxmox-grapple#5]
### Discussed in https://github.com/lingfish/proxmox-grapple/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **ilium007** May 10, 2024</sup>
Not sure what this one is about....

I have an autorestic command I am calling but the ssh binary is not found, presumably because of a $PATH issue:

```
root@pve01:~# cat /etc/proxmox_grapple.yml
production:
  job-end:
    script:
      - '/usr/local/bin/autorestic -c /root/.autorestic.yml --restic-bin /usr/local/bin/restic backup --verbose --all 2>&1 | tee -a /mnt/ext_usb_01/pve01.log'
```

Error in Proxmox log:

```
INFO:     > Executing: /usr/local/bin/restic backup --tag ar:location:ext_usb_01 /mnt/ext_usb_01/dump/
INFO:     Fatal: unable to open repository at sftp:honeyeater-autorestic:/mnt/storage0/winter/pve01/: exec: "ssh": executable file not found in $PATH
```</div>
